### ISSUE TITLE
管理端新增用户birthDay时间字段反序列化报错

### ISSUE THREAD

**Issue by withgakki** [traceJP/starnight#1]
位置：UserController.save
字段：UserEditParam.birthDay
报错:
JSON parse error: Cannot deserialize value of type `java.util.Date` from String "2023-09-03": not a valid representation (error: Failed to parse Date value '2023-09-03': Unparseable date: "2023-09-03"); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2023-09-03": not a valid representation (error: Failed to parse Date value '2023-09-03': Unparseable date: "2023-09-03") at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 154] (through reference chain: com.tracejp.starnight.entity.param.UserEditParam["birthDay"])
或许可以给字段加上@JsonFormat

**Comment by withgakki** [comment]
```java
    /**
     * 生日
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd")
    private Date birthDay;
```

**Comment by traceJP** [comment]
感谢指正，已修复
